INSERT INTO category (id, name) VALUES (1, 'Bakery');
INSERT INTO category (id, name) VALUES (2, 'Dairy');
INSERT INTO category (id, name) VALUES (3, 'Meat');
INSERT INTO category (id, name) VALUES (4, 'Beverages');
INSERT INTO category (id, name) VALUES (5, 'Spices');
INSERT INTO category (id, name) VALUES (6, 'Vegetables');


INSERT INTO product (name, price, category_id) VALUES ('Cake - Cake Sheet Macaroon', 334.29, 1);
INSERT INTO product (name, price, category_id) VALUES ('Corn - Cream, Canned', 529.89, 6);
INSERT INTO product (name, price, category_id) VALUES ('Longos - Grilled Chicken With', 836.7, 3);
INSERT INTO product (name, price, category_id) VALUES ('Peach - Halves', 372.11, 4);
INSERT INTO product (name, price, category_id) VALUES ('Tarragon - Primerba, Paste', 955.46, 5);
INSERT INTO product (name, price, category_id) VALUES ('Cherries - Maraschino,jar', 631.92, 4);
INSERT INTO product (name, price, category_id) VALUES ('Chips - Potato Jalapeno', 354.39, 1);
INSERT INTO product (name, price, category_id) VALUES ('Sauce - White, Mix', 12.58, 5);
INSERT INTO product (name, price, category_id) VALUES ('Water Chestnut - Canned', 356.49, 6);
INSERT INTO product (name, price, category_id) VALUES ('Pepper - Green', 673.27, 6);
INSERT INTO product (name, price, category_id) VALUES ('Pasta - Tortellini, Fresh', 621.49, 1);
INSERT INTO product (name, price, category_id) VALUES ('Ostrich - Fan Fillet', 103.17, 3);
INSERT INTO product (name, price, category_id) VALUES ('Juice - Pineapple, 341 Ml', 773.41, 4);
INSERT INTO product (name, price, category_id) VALUES ('Berry Brulee', 353.91, 1);
INSERT INTO product (name, price, category_id) VALUES ('Mustard - Pommery', 617.53, 5);
INSERT INTO product (name, price, category_id) VALUES ('Baking Soda', 476.08, 5);
INSERT INTO product (name, price, category_id) VALUES ('V8 - Tropical Blend', 832.8, 4);
INSERT INTO product (name, price, category_id) VALUES ('Spice - Paprika', 526.54, 5);
INSERT INTO product (name, price, category_id) VALUES ('Petit Baguette', 665.9, 1);
INSERT INTO product (name, price, category_id) VALUES ('Marsala - Sperone, Fine, D.o.c.', 126.16, 4);
INSERT INTO product (name, price, category_id) VALUES ('Bread - Pumpernickel', 348.15, 1);
INSERT INTO product (name, price, category_id) VALUES ('Galliano', 858.58, 4);
INSERT INTO product (name, price, category_id) VALUES ('Oil - Olive Bertolli', 293.14, 2);
INSERT INTO product (name, price, category_id) VALUES ('Cheese - Ermite Bleu', 671.3, 2);
INSERT INTO product (name, price, category_id) VALUES ('Cheese - Woolwich Goat, Log', 401.16, 2);
INSERT INTO product (name, price, category_id) VALUES ('Soup - French Can Pea', 1.99, 6);
INSERT INTO product (name, price, category_id) VALUES ('Curry Powder Madras', 199.08, 5);
INSERT INTO product (name, price, category_id) VALUES ('Salmon Steak - Cohoe 8 Oz', 438.03, 3);
INSERT INTO product (name, price, category_id) VALUES ('Nut - Chestnuts, Whole', 463.5, 5);
INSERT INTO product (name, price, category_id) VALUES ('Potatoes - Idaho 80 Count', 118.86, 6);
